/* generated from model null*/
/* generated by template coder.DecoderVisitor*/



package htmlred._coder;

import htmlred._parser.*;

import org.antlr.v4.runtime.tree.TerminalNode;
import org.antlr.v4.runtime.*;

public class HTMLRedDecoderVisitor extends HTMLRedAntlrBaseListener {


private HTMLRedDecoder decoder = new HTMLRedDecoder();

public void visitTerminal(TerminalNode node) {
		CommonToken token = (CommonToken)node.getPayload();
	 		System.out.print(decoder.decode(token));
		}

}

