/* generated from model null*/
/* generated by template ast.Class*/
// Class declaration
/* generated by template ast.AstNodeFactory*/



package htmlred._ast;

import static com.google.common.base.Preconditions.*;

import java.util.ArrayList;
import de.se_rwth.commons.logging.Log;



public class HTMLRedNodeFactory {
  
  private static HTMLRedNodeFactory getFactory() {
    if (factory == null) {
      factory = new HTMLRedNodeFactory();
    }
    return factory;
  }
  
  protected static HTMLRedNodeFactory factory = null;

  /* generated by template ast.Attribute*/
   protected  static  HTMLRedNodeFactory factoryASTP = null;

  /* generated by template ast.Attribute*/
   protected  static  HTMLRedNodeFactory factoryASTAlternatives = null;

  /* generated by template ast.Attribute*/
   protected  static  HTMLRedNodeFactory factoryASTB = null;

  /* generated by template ast.Attribute*/
   protected  static  HTMLRedNodeFactory factoryASTI = null;


  protected HTMLRedNodeFactory () {}

  /* generated by template ast.ClassMethod*/
  
   public  static  ASTP createASTP()
   
    { 
     
     /* generated by template ast.factorymethods.Create*/

  {
    if (factoryASTP == null) {
      factoryASTP = getFactory();
    }
    return factoryASTP.doCreateASTP();
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   protected  ASTP doCreateASTP()
   
    { 
     
     /* generated by template ast.factorymethods.DoCreate*/

  {
    return new ASTP();
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   public  static  ASTP createASTP(java.util.List<htmlred._ast.ASTAlternatives> alternativess)
   
    { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(alternativess, "0xA7006_293 Parameter 'alternativess' must not be null.");

     /* generated by template ast.factorymethods.CreateWithParams*/

  {
    if (factoryASTP == null) {
      factoryASTP = getFactory();
    }
    return factoryASTP.doCreateASTP(alternativess);
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   protected  ASTP doCreateASTP(java.util.List<htmlred._ast.ASTAlternatives> alternativess)
   
    { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(alternativess, "0xA7006_732 Parameter 'alternativess' must not be null.");

     /* generated by template ast.factorymethods.DoCreateWithParams*/
 
  {
    return new ASTP(alternativess);
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   public  static  ASTAlternatives createASTAlternatives()
   
    { 
     
     /* generated by template ast.factorymethods.Create*/

  {
    if (factoryASTAlternatives == null) {
      factoryASTAlternatives = getFactory();
    }
    return factoryASTAlternatives.doCreateASTAlternatives();
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   protected  ASTAlternatives doCreateASTAlternatives()
   
    { 
     
     /* generated by template ast.factorymethods.DoCreate*/

  {
    return new ASTAlternatives();
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   public  static  ASTAlternatives createASTAlternatives(htmlred._ast.ASTP p,htmlred._ast.ASTB b,htmlred._ast.ASTI i,String tEXTB)
   
    { 
     /* generated by template ast.factorymethods.ErrorIfNull*/


     /* generated by template ast.factorymethods.CreateWithParams*/

  {
    if (factoryASTAlternatives == null) {
      factoryASTAlternatives = getFactory();
    }
    return factoryASTAlternatives.doCreateASTAlternatives(p, b, i, tEXTB);
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   protected  ASTAlternatives doCreateASTAlternatives(htmlred._ast.ASTP p,htmlred._ast.ASTB b,htmlred._ast.ASTI i,String tEXTB)
   
    { 
     /* generated by template ast.factorymethods.ErrorIfNull*/


     /* generated by template ast.factorymethods.DoCreateWithParams*/
 
  {
    return new ASTAlternatives(p, b, i, tEXTB);
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   public  static  ASTB createASTB()
   
    { 
     
     /* generated by template ast.factorymethods.Create*/

  {
    if (factoryASTB == null) {
      factoryASTB = getFactory();
    }
    return factoryASTB.doCreateASTB();
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   protected  ASTB doCreateASTB()
   
    { 
     
     /* generated by template ast.factorymethods.DoCreate*/

  {
    return new ASTB();
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   public  static  ASTB createASTB(String text)
   
    { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(text, "0xA7006_908 Parameter 'text' must not be null.");

     /* generated by template ast.factorymethods.CreateWithParams*/

  {
    if (factoryASTB == null) {
      factoryASTB = getFactory();
    }
    return factoryASTB.doCreateASTB(text);
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   protected  ASTB doCreateASTB(String text)
   
    { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(text, "0xA7006_332 Parameter 'text' must not be null.");

     /* generated by template ast.factorymethods.DoCreateWithParams*/
 
  {
    return new ASTB(text);
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   public  static  ASTI createASTI()
   
    { 
     
     /* generated by template ast.factorymethods.Create*/

  {
    if (factoryASTI == null) {
      factoryASTI = getFactory();
    }
    return factoryASTI.doCreateASTI();
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   protected  ASTI doCreateASTI()
   
    { 
     
     /* generated by template ast.factorymethods.DoCreate*/

  {
    return new ASTI();
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   public  static  ASTI createASTI(String text)
   
    { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(text, "0xA7006_820 Parameter 'text' must not be null.");

     /* generated by template ast.factorymethods.CreateWithParams*/

  {
    if (factoryASTI == null) {
      factoryASTI = getFactory();
    }
    return factoryASTI.doCreateASTI(text);
  }

  } 

  /* generated by template ast.ClassMethod*/
  
   protected  ASTI doCreateASTI(String text)
   
    { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(text, "0xA7006_215 Parameter 'text' must not be null.");

     /* generated by template ast.factorymethods.DoCreateWithParams*/
 
  {
    return new ASTI(text);
  }

  } 


}

