/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_upstandinghackers_hammer_Hammer_TokenType */

#ifndef _Included_com_upstandinghackers_hammer_Hammer_TokenType
#define _Included_com_upstandinghackers_hammer_Hammer_TokenType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
