/* generated from model null*/
/* generated by template cocos.CoCoInterface*/



package htmlred._cocos;

import htmlred._ast.ASTHTMLRedNode;

public interface HTMLRedASTHTMLRedNodeCoCo {
  public void check(ASTHTMLRedNode node);
}
