/* generated from model null*/
/* generated by template cocos.CoCoInterface*/



package htmlred._cocos;

import htmlred._ast.ASTI;

public interface HTMLRedASTICoCo {
  public void check(ASTI node);
}
