/* generated from model null*/
/* generated by template cocos.CoCoInterface*/



package htmlred._cocos;

import htmlred._ast.ASTP;

public interface HTMLRedASTPCoCo {
  public void check(ASTP node);
}
