/* generated from model null*/
/* generated by template symboltable.ModelingLanguage*/




package htmlred._symboltable;

import java.util.Optional;

import htmlred._parser.HTMLRedParser;
import de.monticore.symboltable.MutableScope;
import de.monticore.symboltable.ResolverConfiguration;

public abstract class HTMLRedLanguage extends de.monticore.CommonModelingLanguage {

  public HTMLRedLanguage(String langName, String fileEnding) {
    super(langName, fileEnding);

    initResolvingFilters();
  }

  @Override
  public HTMLRedParser getParser() {
    return new HTMLRedParser();
  }


  @Override
  public HTMLRedModelLoader getModelLoader() {
    return (HTMLRedModelLoader) super.getModelLoader();
  }

  //@Override
  //protected HTMLRedModelLoader provideModelLoader() {
  //  return new HTMLRedModelLoader(this);
  //}

  protected void initResolvingFilters() {
  }
}
