/* generated from model null*/
/* generated by template mchparser.Actions*/


package htmlred._mch_parser;

import htmlred._mch_parser.tree.*;

import com.upstandinghackers.hammer.ParseResult;
import com.upstandinghackers.hammer.ParsedToken;

/**
 * Class that contains all actions the parser might call while parsing
 */
public class HTMLRedActions 
{
	public static ParsedToken actUndefined(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_Undefined.getValue());
		
		return p.getAst();
	}

	public static ParsedToken actP(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_P.getValue());
		
		return p.getAst();
	}
	public static ParsedToken actAlternatives(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_Alternatives.getValue());
		
		return p.getAst();
	}
	public static ParsedToken actB(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_B.getValue());
		
		return p.getAst();
	}
	public static ParsedToken actI(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_I.getValue());
		
		return p.getAst();
	}
	public static ParsedToken actTT_1(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_1.getValue());
		
		return p.getAst();
	}
	public static ParsedToken actTT_2(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_2.getValue());
		
		return p.getAst();
	}
	public static ParsedToken actTT_3(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_3.getValue());
		
		return p.getAst();
	}
	public static ParsedToken actTT_4(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_4.getValue());
		
		return p.getAst();
	}
	public static ParsedToken actTT_5(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_5.getValue());
		
		return p.getAst();
	}
	public static ParsedToken actTT_6(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_6.getValue());
		
		return p.getAst();
	}
	public static ParsedToken actTEXTB(ParseResult p)
	{		
		p.getAst().setUserTokenType(HTMLRedTreeHelper.UserTokenTypes.UTT_TEXTB.getValue());
		
		return p.getAst();
	}
	

}