/* generated from model null*/
/* generated by template visitor.DelegatorVisitor*/



package htmlred._visitor;

import java.util.Optional;

import de.monticore.ast.ASTNode;

/**
 * Delegator visitor for the <code>HTMLRed</code> language.<br/>
 * <br/>
 * Delegator visitors allow visitor composition. This comes in handy for reuse
 * of visitors implemented for a super language. Note that it is not allowed to
 * run visitors of a super-grammar on an AST of a sub language. Here, a
 * delegator visitor must wrap such a visitor and run it.<br/>
 * Also, note that visiting and endVisiting {@code ASTNode} is delegated to all
 * other registered delegates.<br/><br/>
 * realThis has to be of type HTMLRedDelegatorVisitor. Note that
 * the delegator visitors of sublanguages do inherit from this interface and
 * hence can be used.<br/>
 * Implementing classes must implement the realThis-Pattern. Delegates are
 * always registered to {#getRealThis()}. When changing realThis, the
 * implementing class should put all registered delegates to the new realThis
 * (which also will change the realThis of the delegates themselves).
 * 
 * @see HTMLRedVisitor
 * @see CommonHTMLRedDelegatorVisitor
 */
public interface HTMLRedDelegatorVisitor  extends HTMLRedInheritanceVisitor {

  @Override
  public HTMLRedDelegatorVisitor getRealThis();
  
    
    
    public void set_htmlred__visitor_HTMLRedVisitor(htmlred._visitor.HTMLRedVisitor htmlred__visitor_HTMLRedVisitor);

    public Optional<htmlred._visitor.HTMLRedVisitor> get_htmlred__visitor_HTMLRedVisitor();
    
        @Override
        public default void handle(htmlred._ast.ASTP node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().handle(node);
          }
        }
  
          @Override
          public default void traverse(htmlred._ast.ASTP node) {
            if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
              getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().traverse(node);
            }
          }
 
        @Override
        public default void visit(htmlred._ast.ASTP node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().visit(node);
          }
        }

        @Override
        public default void endVisit(htmlred._ast.ASTP node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().endVisit(node);
          }
        }
        @Override
        public default void handle(htmlred._ast.ASTAlternatives node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().handle(node);
          }
        }
  
          @Override
          public default void traverse(htmlred._ast.ASTAlternatives node) {
            if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
              getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().traverse(node);
            }
          }
 
        @Override
        public default void visit(htmlred._ast.ASTAlternatives node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().visit(node);
          }
        }

        @Override
        public default void endVisit(htmlred._ast.ASTAlternatives node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().endVisit(node);
          }
        }
        @Override
        public default void handle(htmlred._ast.ASTB node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().handle(node);
          }
        }
  
          @Override
          public default void traverse(htmlred._ast.ASTB node) {
            if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
              getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().traverse(node);
            }
          }
 
        @Override
        public default void visit(htmlred._ast.ASTB node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().visit(node);
          }
        }

        @Override
        public default void endVisit(htmlred._ast.ASTB node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().endVisit(node);
          }
        }
        @Override
        public default void handle(htmlred._ast.ASTI node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().handle(node);
          }
        }
  
          @Override
          public default void traverse(htmlred._ast.ASTI node) {
            if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
              getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().traverse(node);
            }
          }
 
        @Override
        public default void visit(htmlred._ast.ASTI node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().visit(node);
          }
        }

        @Override
        public default void endVisit(htmlred._ast.ASTI node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().endVisit(node);
          }
        }
        @Override
        public default void handle(htmlred._ast.ASTHTMLRedNode node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().handle(node);
          }
        }
  
 
        @Override
        public default void visit(htmlred._ast.ASTHTMLRedNode node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().visit(node);
          }
        }

        @Override
        public default void endVisit(htmlred._ast.ASTHTMLRedNode node) {
          if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
            getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().endVisit(node);
          }
        }


  @Override
  public default void visit(ASTNode node) {
    // delegate to all present delegates
      if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
        getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().visit(node);
      }
  }

  @Override
  public default void endVisit(ASTNode node) {
    // delegate to all present delegates 
      if (getRealThis().get_htmlred__visitor_HTMLRedVisitor().isPresent()) {
        getRealThis().get_htmlred__visitor_HTMLRedVisitor().get().endVisit(node);
      }
    }
}
